### ISSUE TITLE
Question regarding the lcnl_codecs.py

### ISSUE THREAD

**Issue by eoncis** [miguelinux314/experiment-notebook#54]
When using the ccsds123-B2 compression algorithm 
In the lcnl_codecs.py, if bytes_per_sample = 2, dynamic_range = 14, why is large_d = 15 (and not 14)?

**Comment by miguelinux314** [comment]
Thank you @eoncis. Indeed, there was a small bug here.

The value of large_d was increased by 1 to avoid large_d=1 (the minimum is 2) for images having dynamic_range = 1. However, this value was incorrectly added as well for all other values of dynamic_range.

It is now solved in the dev branch of the repository, and will be corrected in the next stable release.
